[build]
  command = "ng build --configuration production"
  publish = "dist/transcript-service-generation-app/browser"

[build.environment]
  NODE_VERSION = "20.19.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
