import { OperatingPoint, LanguageCode } from './types';

export const OPERATING_POINTS: { label: string; value: OperatingPoint }[] = [
  { label: 'Estándar', value: 'standard' },
  { label: 'Mejorada', value: 'enhanced' },
];

export interface LanguageOption { label: string; value: LanguageCode }

export const LANGUAGES: LanguageOption[] = [
  { label: 'Automático', value: 'auto' },
  { label: 'Árabe', value: 'ar' },
  { label: 'Bashkir', value: 'ba' },
  { label: 'Vasco (Euskera)', value: 'eu' },
  { label: 'Bielorruso', value: 'be' },
  { label: 'Bengalí', value: 'bn' },
  { label: 'Búlgaro', value: 'bg' },
  { label: 'Cantonés', value: 'yue' },
  { label: 'Catalán', value: 'ca' },
  { label: 'Croata', value: 'hr' },
  { label: 'Checo', value: 'cs' },
  { label: 'Danés', value: 'da' },
  { label: 'Neerlandés (Holandés)', value: 'nl' },
  { label: 'Inglés', value: 'en' },
  { label: 'Esperanto', value: 'eo' },
  { label: 'Estonio', value: 'et' },
  { label: 'Finlandés', value: 'fi' },
  { label: 'Francés', value: 'fr' },
  { label: 'Gallego', value: 'gl' },
  { label: 'Alemán', value: 'de' },
  { label: 'Griego', value: 'el' },
  { label: 'Hebreo', value: 'he' },
  { label: 'Hindi', value: 'hi' },
  { label: 'Húngaro', value: 'hu' },
  { label: 'Indonesio', value: 'id' },
  { label: 'Interlingua', value: 'ia' },
  { label: 'Irlandés (Gaélico)', value: 'ga' },
  { label: 'Italiano', value: 'it' },
  { label: 'Japonés', value: 'ja' },
  { label: 'Coreano', value: 'ko' },
  { label: 'Letón', value: 'lv' },
  { label: 'Lituano', value: 'lt' },
  { label: 'Malayo', value: 'ms' },
  { label: 'Malayo & Inglés (bilingüe)', value: 'en_ms' },
  { label: 'Maltés', value: 'mt' },
  { label: 'Mandarín', value: 'cmn' },
  { label: 'Mandarín & Inglés (bilingüe)', value: 'cmn_en' },
  { label: 'Maratí', value: 'mr' },
  { label: 'Mongol', value: 'mn' },
  { label: 'Noruego', value: 'no' },
  { label: 'Persa', value: 'fa' },
  { label: 'Polaco', value: 'pl' },
  { label: 'Portugués', value: 'pt' },
  { label: 'Rumano', value: 'ro' },
  { label: 'Ruso', value: 'ru' },
  { label: 'Eslovaco', value: 'sk' },
  { label: 'Esloveno', value: 'sl' },
  { label: 'Español', value: 'es' },
  { label: 'Swahili', value: 'sw' },
  { label: 'Sueco', value: 'sv' },
  { label: 'Tagalo (Filipino)', value: 'tl' },
  { label: 'Tamil', value: 'ta' },
  { label: 'Tamil & Inglés (bilingüe)', value: 'en_ta' },
  { label: 'Tailandés', value: 'th' },
  { label: 'Turco', value: 'tr' },
  { label: 'Ucraniano', value: 'uk' },
  { label: 'Urdu', value: 'ur' },
  { label: 'Uigur', value: 'ug' },
  { label: 'Vietnamita', value: 'vi' },
  { label: 'Galés', value: 'cy' },
];


