import { OperatingPoint, LanguageCode } from './types';

export const OPERATING_POINTS: { label: string; value: OperatingPoint }[] = [
  { label: 'Estándar', value: 'standard' },
  { label: 'Mejorada', value: 'enhanced' },
];

export interface LanguageOption { label: string; value: LanguageCode }
export interface SelectOption { label: string; value: string }

export const LANGUAGES: LanguageOption[] = [
  { label: 'Automático', value: 'auto' },
  { label: 'Árabe', value: 'ar' },
  { label: 'Bashkir', value: 'ba' },
  { label: 'Vasco (Euskera)', value: 'eu' },
  { label: 'Bielorruso', value: 'be' },
  { label: 'Bengalí', value: 'bn' },
  { label: 'Búlgaro', value: 'bg' },
  { label: 'Cantonés', value: 'yue' },
  { label: 'Catalán', value: 'ca' },
  { label: 'Croata', value: 'hr' },
  { label: 'Checo', value: 'cs' },
  { label: 'Danés', value: 'da' },
  { label: 'Neerlandés (Holandés)', value: 'nl' },
  { label: 'Inglés', value: 'en' },
  { label: 'Esperanto', value: 'eo' },
  { label: 'Estonio', value: 'et' },
  { label: 'Finlandés', value: 'fi' },
  { label: 'Francés', value: 'fr' },
  { label: 'Gallego', value: 'gl' },
  { label: 'Alemán', value: 'de' },
  { label: 'Griego', value: 'el' },
  { label: 'Hebreo', value: 'he' },
  { label: 'Hindi', value: 'hi' },
  { label: 'Húngaro', value: 'hu' },
  { label: 'Indonesio', value: 'id' },
  { label: 'Interlingua', value: 'ia' },
  { label: 'Irlandés (Gaélico)', value: 'ga' },
  { label: 'Italiano', value: 'it' },
  { label: 'Japonés', value: 'ja' },
  { label: 'Coreano', value: 'ko' },
  { label: 'Letón', value: 'lv' },
  { label: 'Lituano', value: 'lt' },
  { label: 'Malayo', value: 'ms' },
  { label: 'Malayo & Inglés (bilingüe)', value: 'en_ms' },
  { label: 'Maltés', value: 'mt' },
  { label: 'Mandarín', value: 'cmn' },
  { label: 'Mandarín & Inglés (bilingüe)', value: 'cmn_en' },
  { label: 'Maratí', value: 'mr' },
  { label: 'Mongol', value: 'mn' },
  { label: 'Noruego', value: 'no' },
  { label: 'Persa', value: 'fa' },
  { label: 'Polaco', value: 'pl' },
  { label: 'Portugués', value: 'pt' },
  { label: 'Rumano', value: 'ro' },
  { label: 'Ruso', value: 'ru' },
  { label: 'Eslovaco', value: 'sk' },
  { label: 'Esloveno', value: 'sl' },
  { label: 'Español', value: 'es' },
  { label: 'Swahili', value: 'sw' },
  { label: 'Sueco', value: 'sv' },
  { label: 'Tagalo (Filipino)', value: 'tl' },
  { label: 'Tamil', value: 'ta' },
  { label: 'Tamil & Inglés (bilingüe)', value: 'en_ta' },
  { label: 'Tailandés', value: 'th' },
  { label: 'Turco', value: 'tr' },
  { label: 'Ucraniano', value: 'uk' },
  { label: 'Urdu', value: 'ur' },
  { label: 'Uigur', value: 'ug' },
  { label: 'Vietnamita', value: 'vi' },
  { label: 'Galés', value: 'cy' },
];

export const TRANSLATION_TARGET_OPTIONS: SelectOption[] = [
  { value: 'bg', label: 'Búlgaro' },
  { value: 'ca', label: 'Catalán' },
  { value: 'cmn', label: 'Mandarín' },
  { value: 'cs', label: 'Checo' },
  { value: 'da', label: 'Danés' },
  { value: 'de', label: 'Alemán' },
  { value: 'el', label: 'Griego' },
  { value: 'es', label: 'Español' },
  { value: 'et', label: 'Estonio' },
  { value: 'fi', label: 'Finlandés' },
  { value: 'fr', label: 'Francés' },
  { value: 'gl', label: 'Gallego' },
  { value: 'hi', label: 'Hindi' },
  { value: 'hr', label: 'Croata' },
  { value: 'hu', label: 'Húngaro' },
  { value: 'id', label: 'Indonesio' },
  { value: 'it', label: 'Italiano' },
  { value: 'ja', label: 'Japonés' },
  { value: 'ko', label: 'Coreano' },
  { value: 'lt', label: 'Lituano' },
  { value: 'lv', label: 'Letón' },
  { value: 'ms', label: 'Malayo' },
  { value: 'nl', label: 'Neerlandés' },
  { value: 'no', label: 'Noruego' },
  { value: 'pl', label: 'Polaco' },
  { value: 'pt', label: 'Portugués' },
  { value: 'ro', label: 'Rumano' },
  { value: 'ru', label: 'Ruso' },
  { value: 'sk', label: 'Eslovaco' },
  { value: 'sl', label: 'Esloveno' },
  { value: 'sv', label: 'Sueco' },
  { value: 'tr', label: 'Turco' },
  { value: 'uk', label: 'Ucraniano' },
  { value: 'vi', label: 'Vietnamita' },
];


